
  const animals = {
    alligator: new URL("./animals/alligator.png", import.meta.url).href,
    baboon: new URL("./animals/baboon.png", import.meta.url).href,
    chimpanzee: new URL("./animals/chimpanzee.png", import.meta.url).href,
    dingo: new URL("./animals/dingo.png", import.meta.url).href,
    elephant: new URL("./animals/elephant.png", import.meta.url).href,
    frog: new URL("./animals/frog.png", import.meta.url).href,
    gorilla: new URL("./animals/gorilla.png", import.meta.url).href,
    hyena: new URL("./animals/hyena.png", import.meta.url).href,
    impala: new URL("./animals/impala.png", import.meta.url).href,
    jaguar: new URL("./animals/jaguar.png", import.meta.url).href,
    koala: new URL("./animals/koala.png", import.meta.url).href,
    lemur: new URL("./animals/lemur.png", import.meta.url).href,
    macaw: new URL("./animals/macaw.png", import.meta.url).href,
    numbat: new URL("./animals/numbat.png", import.meta.url).href,
    okapi: new URL("./animals/okapi.png", import.meta.url).href,
    panda: new URL("./animals/panda.png", import.meta.url).href,
    quetzal: new URL("./animals/quetzal.png", import.meta.url).href,
    rhinoceros: new URL("./animals/rhinoceros.png", import.meta.url).href,
    snake: new URL("./animals/snake.png", import.meta.url).href,
    tiger: new URL("./animals/tiger.png", import.meta.url).href,
    unau: new URL("./animals/unau.png", import.meta.url).href,
    vervet_monkey: new URL("./animals/vervet_monkey.png", import.meta.url).href,
    warthog: new URL("./animals/warthog.png", import.meta.url).href,
    xenops: new URL("./animals/xenops.png", import.meta.url).href,
    yellow_mongoose: new URL("./animals/yellow_mongoose.png", import.meta.url).href,
    zebra: new URL("./animals/zebra.png", import.meta.url).href,
  };

  const flags = {
    afghanistan: new URL("./flags/afghanistan.png", import.meta.url).href,
    african_union: new URL("./flags/african-union.png", import.meta.url).href,
    australia: new URL("./flags/australia.png", import.meta.url).href,
    brazil: new URL("./flags/brazil.png", import.meta.url).href,
    china: new URL("./flags/china.png", import.meta.url).href,
    cuba: new URL("./flags/cuba.png", import.meta.url).href,
    european_union: new URL("./flags/european-union.png", import.meta.url).href,
    germany: new URL("./flags/germany.png", import.meta.url).href,
    greece: new URL("./flags/greece.png", import.meta.url).href,
    hawaii: new URL("./flags/hawaii.png", import.meta.url).href,
    india: new URL("./flags/india.png", import.meta.url).href,
    iran: new URL("./flags/iran.png", import.meta.url).href,
    italy: new URL("./flags/italy.png", import.meta.url).href,
    japan: new URL("./flags/japan.png", import.meta.url).href,
    philippines: new URL("./flags/philippines.png", import.meta.url).href,
    south_korea: new URL("./flags/south-korea.png", import.meta.url).href,
    thailand: new URL("./flags/thailand.png", import.meta.url).href,
    united_states: new URL("./flags/united-states.png", import.meta.url).href,
    zimbabwe: new URL("./flags/zimbabwe.png", import.meta.url).href,
  };

  const instruments = {
    aeolian_harp: new URL("./instruments/aeolian-harp.png", import.meta.url).href,
    bell_tree: new URL("./instruments/bell-tree.png", import.meta.url).href,
    cuica: new URL("./instruments/cuica.png", import.meta.url).href,
    didgeridoo: new URL("./instruments/didgeridoo.png", import.meta.url).href,
    electric_bass: new URL("./instruments/electric-bass.png", import.meta.url).href,
    harmonica: new URL("./instruments/harmonica.png", import.meta.url).href,
    mbira: new URL("./instruments/mbira.png", import.meta.url).href,
    quijada_de_burro: new URL("./instruments/quijada-de-burro.png", import.meta.url).href,
    violin: new URL("./instruments/violin.png", import.meta.url).href,
    zarb: new URL("./instruments/zarb.png", import.meta.url).href,
  };

  const numbers = {
    apple: new URL("./numbers/apple.png", import.meta.url).href,
    banana: new URL("./numbers/banana.png", import.meta.url).href,
    blueberry: new URL("./numbers/blueberry.png", import.meta.url).href,
    cherry: new URL("./numbers/cherry.png", import.meta.url).href,
    coconut: new URL("./numbers/coconut.png", import.meta.url).href,
    dragonfruit: new URL("./numbers/dragonfruit.png", import.meta.url).href,
    eggplant: new URL("./numbers/eggplant.png", import.meta.url).href,
    fig: new URL("./numbers/fig.png", import.meta.url).href,
    guava: new URL("./numbers/guava.png", import.meta.url).href,
    horned_melon: new URL("./numbers/horned-melon.png", import.meta.url).href,
    indian_gooseberry: new URL("./numbers/indian-gooseberry.png", import.meta.url).href,
    kiwi: new URL("./numbers/kiwi.png", import.meta.url).href,
    mango: new URL("./numbers/mango.png", import.meta.url).href,
    nectarine: new URL("./numbers/nectarine.png", import.meta.url).href,
    pear: new URL("./numbers/pear.png", import.meta.url).href,
    quince: new URL("./numbers/quince.png", import.meta.url).href,
    rambutan: new URL("./numbers/rambutan.png", import.meta.url).href,
    raspberry: new URL("./numbers/raspberry.png", import.meta.url).href,
    starfruit: new URL("./numbers/starfruit.png", import.meta.url).href,
    strawberry: new URL("./numbers/strawberry.png", import.meta.url).href,
    uvas: new URL("./numbers/uvas.png", import.meta.url).href,
    velvet_tamarind: new URL("./numbers/velvet-tamarind.png", import.meta.url).href,
    watermelon: new URL("./numbers/watermelon.png", import.meta.url).href,
  };

  const images = { animals, flags, instruments, numbers };

  export default images;